label to_the_schoolyard:
"Go home, human!"
"That's right! You don't belong here!"
"Hiss! Stay away from me, No Fur!"
"Dark silent glares peered onto Yoah as he walked with Armeria around the schoolyard."   
??? "Are you all right, Yoah?"
yoah "Yeah..."
"Yoah gulped as he speaks." 
"There were even many students that lingers around this place."
"Some whispered around him, while others glared at him."
"Yoah's body began to shake as the beast's threatening words of 'kill him', 'slaughter him', and 'take him to the pack'."
"This school... this negative energy towards Yoah."
"What did the humans do to make this like this?"
??? "Yoah!"
yoah "Huh? Did you say something?"
