label to_the_schoolyard:
"Go home, human!"
"That's right! You don't belong here!"
"Hiss! Stay away from me, No Fur!"
"Dark silent glares peered onto Yoah as he walked with Armeria around the schoolyard."   
??? "Are you all right, Yoah?"
yoah "Yeah..."
"Yoah gulped as he speaks." 
"There were even many students that lingers around this place."
"Some whispered around him, while others glared at him."
"Yoah's body began to shake as the beast's threatening words of 'kill him', 'slaughter him', and 'take him to the pack'."
"This school... this negative energy towards Yoah."
"What did the humans do to make this like this?"
??? "Yoah!"
yoah "Huh? Did you say something?"
??? "I said..."
??? "My name is Armeria! What's yours?"
yoah "Oh, it's..."
yoah "Yoah..."
a "Yoah... what a wonderful name!"
a "I look forward becoming your new friend!"
"Yoah's ears perked, as if he were a beast himself. He looked up at Armeria, who was smiling back at him."
"Him? This plant monster? As his new friend?"
"Suddenly, his lips began to quiver. Forming a broad look that reflected Armeria's face just now."
a "Hahahaha! Wonderful!"
yoah "What is it?" 
a "Oh, it's just that I didn't think a human would smile on their first day!"
a "They would usually be confused or scared!"
yoah "Why should I be scared? It's exciting to be around non-human beings!"
yoah "No, wait. It's like a dream come true! I've always wanted to be the main protagonist in a game!"
yoah "Hmm... that's not right."
a "Ehehehe! For a human being whose life is in dangerous, you sure are a cheery one!"
yoah "Well, yeah! It's not always good to be scared of everything!"
yoah "I should always be positive no matter what happens! Don't you think so too?"
a "..."
"Armeria gasped lightly and widen his eyes."
"Not the type of reaction Yoah expected to be. Did he say something wrong?"
a "The sun is about to set. You would need to meet the Union soon."
yoah "The Union?"
a "Yes, you know these people who surrounds you? They are known as the Union."
a "You'll learn more about them as we listen to their words, understand?"
y "Okay!"
"Yoah jumped gleefully. The 'Union', a name he had never heard before."
"How exciting! He thought to himself."

not_so_good_first_day:
a "Good night."
y "Good night!"
y "Hooray! Let's see what my dorm looks like!"
"*Creck...."
"As soon as Yoah walked inside of his dorm. His legs began to stumble."
y "What the heck?"
"His vision spun around, and his stomach began to churn badly."
"Something was about to come out and so, he were straight to the toilet."
y "Ughhhh..."
y "What's wrong with me?"
"*Bam!*"
a "Yoah! Are you all right?!"
y "Ahhh! Armeria! Can't you knock before you come in?!"
a "Now is not the time for privacy matters! I heard moaning coming from your dorm room!"
a "I thought that you were dying from something, so I got scared."
"Yoah widen his eyes, as he gazed upon Armeria's worried expression."
y "(Can non-humans make that kind of expression?)"
y "(Of course they would, you big dummy!)"
y "(Wouldn't they worry about extinction or something?!)"
"Suddenly, his stomach start churning again and then his face was back on the tiolet."
a "Ah... so I see what's going on."
"Armeria pondered as he observed Yoah."
a "You poor thing! I see that you can't handle this either!"
y "What do you- blech!"
a "I'll keep this brief. It's the territorial markings these beasts made in order to keep you away."
a "As much as I want to take to you to nurse, but it's dangerous for you to go at this time..."
a "Hmmm..."
a "A moment, please."
"As Armeria left, Yoah let out another very unpleasant throw up."
y "Ugh... so that explains the weird smell going around my dorm."
y "Just when I was enjoying my new li- blech!"
a "Come with me."
"Armeria wrapped Yoah's arm around his shoulder and slowly walked with him."
"Pressing his body with his, a sweet scent wavered around the air."
"Honey..."
"Bees would always make those as food for humans."
"Looking at Armeria, there were many leaves and flowers that surrounded his entire body."
"Surprisely, his body was very soft. As if were cuddling a teddy bear, Yoah never wanted to let that go."
"***"
a "I'm afraid this last minute notice had lead to this."
a "You're going to have sleep on my bed."
y "What?! In your bed?!"
y "Why that sounds..."
y "Exciting! Woohoo!"
"Just when Yoah was about to 

