label to_the_schoolyard:
"Go home, human!"
"That's right! You don't belong here!"
"Hiss! Stay away from me, No Fur!"
"Dark silent glares peered onto Yoah as he walked with Armeria around the schoolyard."   
??? "Are you all right, Yoah?"
yoah "Yeah..."
"Yoah gulped as he speaks." 
"There were even many students that lingers around this place."
"Some whispered around him, while others glared at him."
"Yoah's body began to shake as the beast's threatening words of 'kill him', 'slaughter him', and 'take him to the pack'."
"This school... this negative energy towards Yoah."
"What did the humans do to make this like this?"
??? "Yoah!"
yoah "Huh? Did you say something?"
??? "I said..."
??? "My name is Armeria! What's yours?"
yoah "Oh, it's..."
yoah "Yoah..."
a "Yoah... what a wonderful name!"
a "I look forward becoming your new friend!"
"Yoah's ears perked, as if he were a beast himself. He looked up at Armeria, who was smiling back at him."
"Him? This plant monster? As his new friend?"
"Suddenly, his lips began to quiver. Forming a broad look that reflected Armeria's face just now."
a "Hahahaha! Wonderful!"
yoah "What is it?" 
a "Oh, it's just that I didn't think a human would smile on their first day!"
a "They would usually be confused or scared!"
yoah "Why should I be scared? It's exciting to be around non-human beings!"
yoah "No, wait. It's like a dream come true! I've always wanted to be the main protagonist in a game!"
yoah "Hmm... that's not right."
a "Ehehehe! For a human being whose life is in dangerous, you sure are a cheery one!"
yoah "Well, yeah! It's not always good to be scared of everything!"
yoah "I should always be positive no matter what happens! Don't you think so too?"
a "..."
"Armeria gasped lightly and widen his eyes."
"Not the type of reaction Yoah expected to be. Did he say something wrong?"
a "The sun is about to set. You would need to meet the Union soon."
yoah "The Union?"
a "Yes, you know these people who surrounds you? They are known as the Union."
a "You'll learn more about them as we listen to their words, understand?"
y "Okay!"
"Yoah jumped gleefully. The 'Union', a name he had never heard before."
"How exciting! He thought to himself."

not_so_good_first_day:
a "Good night."
y "Good night!"
y "Hooray! Let's see what my dorm looks like!"
"*Creck...."
"As soon as Yoah walked inside of his dorm. His legs began to stumble."
y "What the heck?"
"His vision spun around, and his stomach began to churn badly."
"Something was about to come out and so, he were straight to the toilet."
